export { default as Startup } from './Startup/Startup';
export { default as Example } from './Example/Example';
export { default as Home } from './Home/Home';
export { default as Favorit } from './Favorit/Favorit';
export { default as Ticket } from './Ticket/Ticket';
export { default as Profile } from './Profile/Profile';
export { default as MoveDetails } from './Moviedetails/Moviedetails';
export { default as DetailTiket} from './DetailTiket/DetailTiket';
export { default as ConfirmationTiket} from './ConfirmationTiket/ConfirmationTiket';
export { default as Payment} from './Payment/Payment';
export { default as Login} from './Login/Login';
export { default as Register} from './Register/Register';
export { default as EditProfile} from './EditProfile/EditProfile';