export const DataFilem = [
  {
    id: '1',
    Judul: 'Poltergeist (2015)',
    gambar1: require('../theme/assets/images/PosterBadoet.png'),
    day: 'Release date',
    IconStar: require('../theme/assets/images/IconStar.png'),
    IconTime: require('../theme/assets/images/IconTime.png'),
    Gendre: 'Genre',
    Icon4k: require('../theme/assets/images/Icon4K.png'),
    date: 'December 9, 2020',
    action: 'Action',
    Scifi: 'Sci-Fi',
    videoId: 'HD2sz9RVzfM',
    sinopsis:
      'Rey (Daisy Ridley) finally manages to find the legendary Jedi knight, Luke Skywalker (Mark Hamill) on an island with a magical aura. The heroes of The Force Awakens including Leia, Finn Read more.',
  },
  {
    id: '2',
    Judul: 'Venom (2020)',
    gambar1: require('../theme/assets/images/VenomSlider.png'),
    day: 'Release date',
    IconStar: require('../theme/assets/images/IconStar.png'),
    IconTime: require('../theme/assets/images/IconTime.png'),
    Gendre: 'Genre',
    Icon4k: require('../theme/assets/images/Icon4K.png'),
    date: 'December 9, 2020',
    action: 'Action',
    Scifi: 'Sci-Fi',
    videoId: 'u9Mv98Gr5pY',
    sinopsis:
      'Rey (Daisy Ridley) finally manages to find the legendary Jedi knight, Luke Skywalker (Mark Hamill) on an island with a magical aura. The heroes of The Force Awakens including Leia, Finn Read more.',
  },
  {
    id: '3',
    Judul: 'Knives Out (2019)',
    gambar1: require('../theme/assets/images/Poster1.png'),
    day: 'Release date',
    IconStar: require('../theme/assets/images/IconStar.png'),
    IconTime: require('../theme/assets/images/IconTime.png'),
    Gendre: 'Genre',
    Icon4k: require('../theme/assets/images/Icon4K.png'),
    date: 'December 9, 2019',
    action: 'Action',
    Scifi: 'Sci-Fi',
    videoId: 'gj5ibYSz8C0',
    sinopsis:
      'Rey (Daisy Ridley) finally manages to find the legendary Jedi knight, Luke Skywalker (Mark Hamill) on an island with a magical aura. The heroes of The Force Awakens including Leia, Finn Read more.',
  },
  {
    id: '4',
    Judul: 'SevenTh Son (2019)',
    gambar1: require('../theme/assets/images/PosterSevenOn.png'),
    day: 'Release date',
    IconStar: require('../theme/assets/images/IconStar.png'),
    IconTime: require('../theme/assets/images/IconTime.png'),
    Gendre: 'Genre',
    Icon4k: require('../theme/assets/images/Icon4K.png'),
    date: 'December 9, 2019',
    action: 'Action',
    Scifi: 'Sci-Fi',
    videoId: '5i90Qr0Qi6w',
    sinopsis:
      'Rey (Daisy Ridley) finally manages to find the legendary Jedi knight, Luke Skywalker (Mark Hamill) on an island with a magical aura. The heroes of The Force Awakens including Leia, Finn Read more.',
  },
  {
    id: '5',
    Judul: 'Smurf (2020)',
    gambar1: require('../theme/assets/images/Poster3.png'),
    day: 'Release date',
    IconStar: require('../theme/assets/images/IconStar.png'),
    IconTime: require('../theme/assets/images/IconTime.png'),
    Gendre: 'Genre',
    Icon4k: require('../theme/assets/images/Icon4K.png'),
    date: 'December 9, 2020',
    action: 'Action',
    Scifi: 'Sci-Fi',
    videoId: 'yP2VHXPsTtQ',
    sinopsis:
      'Rey (Daisy Ridley) finally manages to find the legendary Jedi knight, Luke Skywalker (Mark Hamill) on an island with a magical aura. The heroes of The Force Awakens including Leia, Finn Read more.',
  },
  {
    id: '6',
    Judul: 'Joker (2019)',
    gambar1: require('../theme/assets/images/posterJoker.png'),
    day: 'Release date',
    IconStar: require('../theme/assets/images/IconStar.png'),
    IconTime: require('../theme/assets/images/IconTime.png'),
    Gendre: 'Genre',
    Icon4k: require('../theme/assets/images/Icon4K.png'),
    date: 'December 9, 2019',
    action: 'Action',
    Scifi: 'Sci-Fi',
    videoId: '5VjP45rdU7w',
    sinopsis:
      'Rey (Daisy Ridley) finally manages to find the legendary Jedi knight, Luke Skywalker (Mark Hamill) on an island with a magical aura. The heroes of The Force Awakens including Leia, Finn Read more.',
  },
  {
    id: '7',
    Judul: 'Justice League',
    gambar1: require('../theme/assets/images/JusticeLeague.png'),
    day: 'Release date',
    IconStar: require('../theme/assets/images/IconStar.png'),
    IconTime: require('../theme/assets/images/IconTime.png'),
    Gendre: 'Genre',
    Icon4k: require('../theme/assets/images/Icon4K.png'),
    date: 'December 9, 2019',
    action: 'Action',
    Scifi: 'Sci-Fi',
    videoId: 'uC9qU3X1JgM',
    sinopsis:
      'Rey (Daisy Ridley) finally manages to find the legendary Jedi knight, Luke Skywalker (Mark Hamill) on an island with a magical aura. The heroes of The Force Awakens including Leia, Finn Read more.',
  },
  {
    id: '8',
    Judul: 'Jurassic Word',
    gambar1: require('../theme/assets/images/JurassicWord.png'),
    day: 'Release date',
    IconStar: require('../theme/assets/images/IconStar.png'),
    IconTime: require('../theme/assets/images/IconTime.png'),
    Gendre: 'Genre',
    Icon4k: require('../theme/assets/images/Icon4K.png'),
    date: 'December 9, 2022',
    action: 'Action',
    Scifi: 'Sci-Fi',
    videoId: 'n-hzq5TOLdM',
    sinopsis:
      'Rey (Daisy Ridley) finally manages to find the legendary Jedi knight, Luke Skywalker (Mark Hamill) on an island with a magical aura. The heroes of The Force Awakens including Leia, Finn Read more.',
  },
  {
    id: '9',
    Judul: 'Avatar (2023)',
    gambar1: require('../theme/assets/images/Avatar.png'),
    day: 'Release date',
    IconStar: require('../theme/assets/images/IconStar.png'),
    IconTime: require('../theme/assets/images/IconTime.png'),
    Gendre: 'Genre',
    Icon4k: require('../theme/assets/images/Icon4K.png'),
    date: 'December 9, 2022',
    action: 'Action',
    Scifi: 'Sci-Fi',
    videoId: 'X47sEzHdPI0',
    sinopsis:
      'Rey (Daisy Ridley) finally manages to find the legendary Jedi knight, Luke Skywalker (Mark Hamill) on an island with a magical aura. The heroes of The Force Awakens including Leia, Finn Read more.',
  },
  {
    id: '10',
    Judul: 'Guardians of Galaxy',
    gambar1: require('../theme/assets/images/GuardiansofGalaxy.png'),
    day: 'Release date',
    IconStar: require('../theme/assets/images/IconStar.png'),
    IconTime: require('../theme/assets/images/IconTime.png'),
    Gendre: 'Genre',
    Icon4k: require('../theme/assets/images/Icon4K.png'),
    date: 'July 19, 2023',
    action: 'Action',
    Scifi: 'Sci-Fi',
    videoId: 'u3V5KDHRQvk',
    sinopsis:
      'Rey (Daisy Ridley) finally manages to find the legendary Jedi knight, Luke Skywalker (Mark Hamill) on an island with a magical aura. The heroes of The Force Awakens including Leia, Finn Read more.',
  },
  {
    id: '11',
    Judul: 'Hulk (2020)',
    gambar1: require('../theme/assets/images/Hullk.png'),
    day: 'Release date',
    IconStar: require('../theme/assets/images/IconStar.png'),
    IconTime: require('../theme/assets/images/IconTime.png'),
    Gendre: 'Genre',
    Icon4k: require('../theme/assets/images/Icon4K.png'),
    date: 'July 20, 2020',
    action: 'Action',
    Scifi: 'Sci-Fi',
    videoId: 'DX5kJ2hYQcQ',
    sinopsis:
      'Rey (Daisy Ridley) finally manages to find the legendary Jedi knight, Luke Skywalker (Mark Hamill) on an island with a magical aura. The heroes of The Force Awakens including Leia, Finn Read more.',
  },
  {
    id: '12',
    Judul: 'Yakuza (2020)',
    gambar1: require('../theme/assets/images/Poster.png'),
    day: 'Release date',
    IconStar: require('../theme/assets/images/IconStar.png'),
    IconTime: require('../theme/assets/images/IconTime.png'),
    Gendre: 'Genre',
    Icon4k: require('../theme/assets/images/Icon4K.png'),
    date: 'July 21, 2020',
    action: 'Action',
    Scifi: 'Sci-Fi',
    videoId: 'LHLE8tnduU4',
    sinopsis:
      'Rey (Daisy Ridley) finally manages to find the legendary Jedi knight, Luke Skywalker (Mark Hamill) on an island with a magical aura. The heroes of The Force Awakens including Leia, Finn Read more.',
  },
  {
    id: '13',
    Judul: 'Spideman No way Home',
    gambar1: require('../theme/assets/images/NowayHome.png'),
    day: 'Release date',
    IconStar: require('../theme/assets/images/IconStar.png'),
    IconTime: require('../theme/assets/images/IconTime.png'),
    Gendre: 'Genre',
    Icon4k: require('../theme/assets/images/Icon4K.png'),
    date: 'July 21, 2020',
    action: 'Action',
    Scifi: 'Sci-Fi',
    videoId: 'JfVOs4VSpmA',
    sinopsis:
      'Rey (Daisy Ridley) finally manages to find the legendary Jedi knight, Luke Skywalker (Mark Hamill) on an island with a magical aura. The heroes of The Force Awakens including Leia, Finn Read more.',
  },
  {
    id: '14',
    Judul: 'The Wolverine',
    gambar1: require('../theme/assets/images/thewolverine.png'),
    day: 'Release date',
    IconStar: require('../theme/assets/images/IconStar.png'),
    IconTime: require('../theme/assets/images/IconTime.png'),
    Gendre: 'Genre',
    Icon4k: require('../theme/assets/images/Icon4K.png'),
    date: 'July 21, 2020',
    action: 'Action',
    Scifi: 'Sci-Fi',
    videoId: 'nUXZpPNZQrg',
    sinopsis:
      'Rey (Daisy Ridley) finally manages to find the legendary Jedi knight, Luke Skywalker (Mark Hamill) on an island with a magical aura. The heroes of The Force Awakens including Leia, Finn Read more.',
  },
  {
    id: '15',
    Judul: 'Venom Vs Spiderman (2021)',
    gambar1: require('../theme/assets/images/venom22.png'),
    day: 'Release date',
    IconStar: require('../theme/assets/images/IconStar.png'),
    IconTime: require('../theme/assets/images/IconTime.png'),
    Gendre: 'Genre',
    Icon4k: require('../theme/assets/images/Icon4K.png'),
    date: 'July 21, 2020',
    action: 'Action',
    Scifi: 'Sci-Fi',
    videoId: 'u9Mv98Gr5pY',
    sinopsis:
      'Rey (Daisy Ridley) finally manages to find the legendary Jedi knight, Luke Skywalker (Mark Hamill) on an island with a magical aura. The heroes of The Force Awakens including Leia, Finn Read more.',
  },
  {
    id: '16',
    Judul: 'Freedom (2022)',
    gambar1: require('../theme/assets/images/Fredom.png'),
    day: 'Release date',
    IconStar: require('../theme/assets/images/IconStar.png'),
    IconTime: require('../theme/assets/images/IconTime.png'),
    Gendre: 'Genre',
    Icon4k: require('../theme/assets/images/Icon4K.png'),
    date: 'July 21, 2020',
    action: 'Action',
    Scifi: 'Sci-Fi',
    videoId: 'Rt0kp4VW1cI',
    sinopsis:
      'Rey (Daisy Ridley) finally manages to find the legendary Jedi knight, Luke Skywalker (Mark Hamill) on an island with a magical aura. The heroes of The Force Awakens including Leia, Finn Read more.',
  },
  {
    id: '17',
    Judul: 'Batman Vs Supeman (2019)',
    gambar1: require('../theme/assets/images/SupemanVsBatman.png'),
    day: 'Release date',
    IconStar: require('../theme/assets/images/IconStar.png'),
    IconTime: require('../theme/assets/images/IconTime.png'),
    Gendre: 'Genre',
    Icon4k: require('../theme/assets/images/Icon4K.png'),
    date: 'July 21, 2019',
    action: 'Action',
    Scifi: 'Sci-Fi',
    videoId: '0WWzgGyAH6Y',
    sinopsis:
      'Rey (Daisy Ridley) finally manages to find the legendary Jedi knight, Luke Skywalker (Mark Hamill) on an island with a magical aura. The heroes of The Force Awakens including Leia, Finn Read more.',
  },
  {
    id: '18',
    Judul: 'Marvel Avengers Civil Wars',
    gambar1: require('../theme/assets/images/benercaptenamerica.png'),
    day: 'Release date',
    IconStar: require('../theme/assets/images/IconStar.png'),
    IconTime: require('../theme/assets/images/IconTime.png'),
    Gendre: 'Genre',
    Icon4k: require('../theme/assets/images/Icon4K.png'),
    date: 'July 21, 2020',
    action: 'Action',
    Scifi: 'Sci-Fi',
    videoId: 'dKrVegVI0Us',
    sinopsis:
      'Rey (Daisy Ridley) finally manages to find the legendary Jedi knight, Luke Skywalker (Mark Hamill) on an island with a magical aura. The heroes of The Force Awakens including Leia, Finn Read more.',
  },
  {
    id: '19',
    Judul: 'Back Panter (2022)',
    gambar1: require('../theme/assets/images/Backpanter.png'),
    day: 'Release date',
    IconStar: require('../theme/assets/images/IconStar.png'),
    IconTime: require('../theme/assets/images/IconTime.png'),
    Gendre: 'Genre',
    Icon4k: require('../theme/assets/images/Icon4K.png'),
    date: 'July 21, 2022',
    action: 'Action',
    Scifi: 'Sci-Fi',
    videoId: 'RlOB3UALvrQ',
    sinopsis:
      'Rey (Daisy Ridley) finally manages to find the legendary Jedi knight, Luke Skywalker (Mark Hamill) on an island with a magical aura. The heroes of The Force Awakens including Leia, Finn Read more.',
  },
  {
    id: '20',
    Judul: 'Star Wars (2021)',
    gambar1: require('../theme/assets/images/StarWar.png'),
    day: 'Release date',
    IconStar: require('../theme/assets/images/IconStar.png'),
    IconTime: require('../theme/assets/images/IconTime.png'),
    Gendre: 'Genre',
    Icon4k: require('../theme/assets/images/Icon4K.png'),
    date: 'July 21, 2021',
    action: 'Action',
    Scifi: 'Sci-Fi',
    videoId: '8Qn_spdM5Zg',
    sinopsis:
      'Rey (Daisy Ridley) finally manages to find the legendary Jedi knight, Luke Skywalker (Mark Hamill) on an island with a magical aura. The heroes of The Force Awakens including Leia, Finn Read more.',
  },
  {
    id: '21',
    Judul: 'Aquaman (2019)',
    gambar1: require('../theme/assets/images/movieposter.png'),
    day: 'Release date',
    IconStar: require('../theme/assets/images/IconStar.png'),
    IconTime: require('../theme/assets/images/IconTime.png'),
    Gendre: 'Genre',
    Icon4k: require('../theme/assets/images/Icon4K.png'),
    date: 'July 21, 2021',
    action: 'Action',
    Scifi: 'Sci-Fi',
    videoId: 'CtXhCJeAZDA',
    sinopsis:
      'Rey (Daisy Ridley) finally manages to find the legendary Jedi knight, Luke Skywalker (Mark Hamill) on an island with a magical aura. The heroes of The Force Awakens including Leia, Finn Read more.',
  },
  {
    id: '22',
    Judul: 'Puss in Boots The Last Wish',
    gambar1: require('../theme/assets/images/movieposter22.png'),
    day: 'Release date',
    IconStar: require('../theme/assets/images/IconStar.png'),
    IconTime: require('../theme/assets/images/IconTime.png'),
    Gendre: 'Genre',
    Icon4k: require('../theme/assets/images/Icon4K.png'),
    date: 'July 21, 2021',
    action: 'Action',
    Scifi: 'Sci-Fi',
    videoId: 'Uwy7Hr4yM1M',
    sinopsis:
      'Rey (Daisy Ridley) finally manages to find the legendary Jedi knight, Luke Skywalker (Mark Hamill) on an island with a magical aura. The heroes of The Force Awakens including Leia, Finn Read more.',
  },
  {
    id: '23',
    Judul: 'Madagascar 2 Escape to Africa',
    gambar1: require('../theme/assets/images/Madagaskar.png'),
    day: 'Release date',
    IconStar: require('../theme/assets/images/IconStar.png'),
    IconTime: require('../theme/assets/images/IconTime.png'),
    Gendre: 'Genre',
    Icon4k: require('../theme/assets/images/Icon4K.png'),
    date: 'July 21, 2021',
    action: 'Action',
    Scifi: 'Sci-Fi',
    videoId: 'e8L5j2ac-lE',
    sinopsis:
      'Rey (Daisy Ridley) finally manages to find the legendary Jedi knight, Luke Skywalker (Mark Hamill) on an island with a magical aura. The heroes of The Force Awakens including Leia, Finn Read more.',
  },
  {
    id: '24',
    Judul: 'Walle',
    gambar1: require('../theme/assets/images/Walle.png'),
    day: 'Release date',
    IconStar: require('../theme/assets/images/IconStar.png'),
    IconTime: require('../theme/assets/images/IconTime.png'),
    Gendre: 'Genre',
    Icon4k: require('../theme/assets/images/Icon4K.png'),
    date: 'July 21, 2021',
    action: 'Action',
    Scifi: 'Sci-Fi',
    videoId: 'e_XApMM7jro',
    sinopsis:
      'Rey (Daisy Ridley) finally manages to find the legendary Jedi knight, Luke Skywalker (Mark Hamill) on an island with a magical aura. The heroes of The Force Awakens including Leia, Finn Read more.',
  },
  {
    id: '25',
    Judul: 'Walle',
    gambar1: require('../theme/assets/images/It.png'),
    day: 'Release date',
    IconStar: require('../theme/assets/images/IconStar.png'),
    IconTime: require('../theme/assets/images/IconTime.png'),
    Gendre: 'Genre',
    Icon4k: require('../theme/assets/images/Icon4K.png'),
    date: 'July 21, 2021',
    action: 'Action',
    Scifi: 'Sci-Fi',
    videoId: 'f9-sfBQ6ehE',
    sinopsis:
      'Rey (Daisy Ridley) finally manages to find the legendary Jedi knight, Luke Skywalker (Mark Hamill) on an island with a magical aura. The heroes of The Force Awakens including Leia, Finn Read more.',
  },
  {
    id: '26',
    Judul: 'Turbo',
    gambar1: require('../theme/assets/images/Turboo.png'),
    day: 'Release date',
    IconStar: require('../theme/assets/images/IconStar.png'),
    IconTime: require('../theme/assets/images/IconTime.png'),
    Gendre: 'Genre',
    Icon4k: require('../theme/assets/images/Icon4K.png'),
    date: 'July 21, 2013',
    action: 'Action',
    Scifi: 'Sci-Fi',
    videoId: 'VlRtm8Gh9PQ',
    sinopsis:
      'Rey (Daisy Ridley) finally manages to find the legendary Jedi knight, Luke Skywalker (Mark Hamill) on an island with a magical aura. The heroes of The Force Awakens including Leia, Finn Read more.',
  },
];
